### ISSUE TITLE
How long does it take to finish the simulations?

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH-UI#10]
This will be displayed for the user, together with the size of the results to be saved. 
Factors to consider:
1. number of trials
2. number of tasks

**Comment by BHagedorn-IDM** [comment]
So it turns out that the function that used to exist in R for doing this has been deprecated. I'm talking to Michelle and Marita about how they tested their software prior to the APHRC training to see if we can borrow their methods. I've also asked for VMs as an alternative for testing.

**Comment by BHagedorn-IDM** [comment]
@MeWu-IDM Alternative design/implementation concept. Is it possible to set up short function to run when someone clicks the "next" button form the validation page? This would run a very brief calculation and calculate the time required to do so on their location machine. We then take that as a ratio to how long it takes to run on my machine, and use this value to scale up the estimate. What do you think? 

If you can confirm that it is okay to put this into the "next" button as described above, then I think this works and I will set up the script + function. Might need your help to integrate, but I should be able to get it mostly ready.

**Comment by BHagedorn-IDM** [comment]
Formulas for running on my computer specs below:

Run time (seconds) = -18.51 + .03955 * number of runs + .9659 * number of years + .2366 * number of tasks
Run time (seconds) = max(calc above, 10 sec) to avoid having extremely small or negative numbers.

File size (KB) = -12740 + 18.29 * number of runs + 390.5 * number of years + 296.7 * number of tasks 
Fill size (KB) = max(calc above, 3000 KB) to avoid having extremely small or negative numbers.

**Comment by BHagedorn-IDM** [comment]
Function for estimating the scaling ratio is below. This function should be called when a user starts to set up a new simulation and the scaling ratio stored. When they enter the number of runs, use the run time described in the above comment, multiplied by the scaling ratio. (The 1.10 multiplier is the uncertainty factor based on my computer's run times, this should not change, just leave as is.)

#Function to generate scaling ratio
run_benchmark = function(n=200){
  
  reference <- 0.09344006 # Time in seconds that a fast computer takes to run this benchmark 
  start <- Sys.time() #Start timing
  matrix_a <- matrix(rnorm(n*1000),nrow=n, ncol=1000)
  result <- t(matrix_a) %*% matrix_a # Perform the big computation 
  timeelapsed <- Sys.time() - start # Stop timing
  ratio <- as.numeric(timeelapsed) / reference  
  return(ratio)

}

scalingratio <- run_benchmark() * 1.10

**Comment by BHagedorn-IDM** [comment]
@MeWu-IDM  I think you should now have everything that you need to plug these calculations in. The text should then read "The run time may take up to X minutes to complete." etc.

**Comment by MeWu-IDM** [comment]
@BHagedorn-IDM 
could you try the microbenchmark package to run the exact function you did with system.time

when I run the below function, it merely takes 1e-3 milliseconds so I was wondering if we are running different benchmark functions it seems odd to be 1000 more time faster than you

 ```
f <- function(n=1000){
    matrix_a <- matrix(rnorm(1000),nrow=n, ncol=1000)
    result <- t(matrix_a) %% matrix_a
  }
  res <- microbenchmark(f(), unit="millisecond", times=50L)
```
you can read from this http://adv-r.had.co.nz/Performance.html for more details

**Comment by MeWu-IDM** [comment]
benchmark estimation is integrated to the simulation steps
