### ISSUE TITLE
03/05 small bugs

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH-UI#13]
1. "Target HRH utilization" autoformat not reliable, change to use (%) for simplification.
2. Display: vertical height. The bottom buttons are blocked by banner. Need to fix window size when deployed.
3. Show results -> "Print PDF of Summary Plots" -> hide green button when processing.
4. Show results -> "Print PDF of Summary Plots" -> seasonality plots are not printed, need to remove "plotly"

**Comment by MeWu-IDM** [comment]
1. Change to %
2. add margin-bottom to make sure the button div has room for footer
3. use shinyjs::hide when user click download
4. seasonality is printed in pdf now
