### ISSUE TITLE
Failure to launch - shinyStore

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#15]
After downloading and trying to run the app for the first time, I am having a problem with shinyStore. 

My initial process:
* Download the branch.
* Run install_packages.R (worked fine).
* Run shiny::runApp (failed). Error: "Error in library(shinyStore) : there is no package called ‘shinyStore’".
* Added shinyStore to install_packages and reran. Failed because there is no package called shinyStore. 
* Using the RStudio menus, Tools > Install packages > found there is a package called shinyStorePlus. Installed this and updated app.R to call this library instead. 
* Ran app.R and got an error at line 28: "Error in shinyStorePlus::initStore("store", "PACE-HRH-UI-store") : unused arguments ("store", "PACE-HRH-UI-store")". 

With some searching, I found the package. The following code works and I've added it to the install_packages.R script but I'm not sure if this is the best approach. 

library(devtools)
install_github("trestletech/shinyStore")

**Comment by MeWu-IDM** [comment]
Need to address it in deployment process

**Comment by MeWu-IDM** [comment]
this should have been fixed: https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/blob/76be8bc545ceaa78d0434fb0fe43ca54f267a640/install_packages.R#L16
