### ISSUE TITLE
Edit inputs instructions for validation step

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#16]
So it's not obvious from the current set up what a user is supposed to do if they are in the validation step and don't like what they see. We need to provide some instructions or a button or something that they can use to correct something that is wrong. It's not really much of a validation if they can't fix it! Sorry I didn't think about this before. 

This is where in the process that I mean, and the update will need to sit on all validation plot sub-pages: 
![image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/27299324/1d6e0a36-907c-4e5f-8a53-0c43f9490723)

**Comment by MeWu-IDM** [comment]
We currently add some text like this, let's discuss how to do this 
![image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/40474438/58cdbe0c-3e79-4bdc-9bf4-4e7296f834e4)

**Comment by BHagedorn-IDM** [comment]
Can we update this text box to the following?

"Validate that your data inputs are correct by reviewing these data summary plots. If you find something that does not look correct, navigate to the input Excel file in your project folder, update the values, save the file, and restart this application. The program will reload these input values and you can check again that they have been updated correctly.

The population pyramid represents the portion of the population that is of a particular age and gender at the start of the modeled timeframe, and should match your current local demographics. Fertility and mortality rates will determine how this population changes over time, and the values should match your current situation. Seasonality is applied to particular tasks performed by the health worker(s) and represents the changes in demand for healthcare throughout the year."

**Comment by MeWu-IDM** [comment]
this is fixed in https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/blob/b33bd5534c70b4c7663bb811b3ce972efad118d6/R/tooltips.R#L13
