### ISSUE TITLE
Spreadsheet input values validation - back into UI?

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#17]
I think in the process of designing the UI, we lost the original validation steps. E.g., checking that seasonality added to 1, that growth rates weren't extraordinary, etc. Can we bring that back as a step in the UI validation process?

**Comment by MeWu-IDM** [comment]
@BHagedorn-IDM 
I think we previously discuss not to show all the detailed validation report because UI users are not savvy about the data validation process but let's discuss what plots that we would like to bring back and add them

**Comment by MeWu-IDM** [comment]
the validation report is not available in step 2
