### ISSUE TITLE
Duplicate scenario names?

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#18]
Is there a way to ensure that a user can't enter a scenario run name that they've previously used? I'm starting to think about ways that people might break things, and while we could tell the difference between them using the time stamp, it would likely cause confusion for the user (and maybe the code?) if they had two runs named the same thing.

**Comment by MeWu-IDM** [comment]
@BHagedorn-IDM 
currently it is not allowed to have duplicate names because the storage location will collide
![image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/40474438/fe7ff98d-bd6d-4fef-bb17-81b8b06c4a3a)
Let me know if this is ok for your concern
