### ISSUE TITLE
Bug - read.xlsx error?

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#19]
I was running the app perfectly fine today, but had to close my R to save battery. Now that I've reopened, I am getting a very strange error message when I run the app. It works fine to open, set parameters, review validation, and name the test run. But then once I click "run simulations" it errors out, closes the app and reports as follows. I am currently unable to get the app to the results pages. :-(

![image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/27299324/7590e1ca-5f6d-44b8-b5aa-644d3ad74a98)

This is very bizarre because I was running sims just fine earlier. A few notes that might help with debugging: 

One is that the error reports a problem with "read.xlsx" but the function that I am familiar with is read_xlsx, so I'm not sure if there might be a spelling error that got introduced somehow? That doesn't seem possible, but maybe worth checking.

Second is that I had a different error first, which I resolved with a package update to htmltools. I had been running an earlier version and my RStudio wouldn't launch the app until I upgraded to the most recent version. Maybe this is driving a cascading effect that I am unable to identify?

Third is that I've checked to make sure that the library(readxl) is loaded, which is the package that has read_xslx. So that isn't the issue.

Last is that I did add the ggrepel package, which could have caused an issue? I didn't end up using it yet, so I removed it from the library call load list, but that didn't solve the problem. I don't think this is the source of the issue, but just FYI in case.

**Comment by MeWu-IDM** [comment]
- I will change to use read_xlsx as read.xlsx is from a different package openxlsx (we used it for writing csv, maybe later can also be replaced by writexl package)
- for the ggrepel package it was already in the installpackage script so I will remove the duplicate ones but I did not find usage for it (position_nudge_repel or geom_text_repel, geom_label_repel) so it might be from an earlier ggplot code that is no longer in use, we will track this when we try to work on deployment

**Comment by MeWu-IDM** [comment]
this has been fixed to use read_xlsx
