### ISSUE TITLE
Clarify sim results saving and retrieving, comparing results

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#2]
The wireframe and documents do not have story for saving and retrieving, comparing results
We need to discuss how to implement this, currently shiny offers below[ persistent storage options](https://shiny.posit.co/r/articles/build/persistent-data-storage/) (server side)
for simplicity, we may just use local file system, but may also need client side storage to save users' history (what names they chose)
https://github.com/trestletech/shinyStore was used in the demo to store  which seems promising but further experimenting on how they work with modules need to be done.
In this ticket, we need to clarify each button's story:
![image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/40474438/19fc0263-22bb-4aec-9994-11393a4662cf)

some example questions:
- Whart are the summary plot pdf, should this be produced by PACE package?
- What are the files included in the storage (one csv for each scenarios or all in one csv,  and cross scenario comparison plots?)
- What does comparison look like, how many can be selected to compare?

[PACE-HRH UI Wireframe Option C v2.pdf](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/files/14013683/PACE-HRH.UI.Wireframe.Option.C.v2.pdf)
[Response to VW re MVP design.docx](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/files/14013692/Response.to.VW.re.MVP.design.docx)
[PACE-HRH UI paper prototype v1 itemized adjustments.docx](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/files/14013710/PACE-HRH.UI.paper.prototype.v1.itemized.adjustments.docx)

**Comment by MeWu-IDM** [comment]
Update:
- Remove "save results for later comparision" button and use "Select previous results" to redirect to the result view page
![image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/40474438/75702f4f-96bb-46f2-b36a-b58bf05cebd5)

**Comment by rhanIDM** [comment]
We have discussed and decided to implement in the following ways:
1.) Sample result plots using summary stats are currently printed to pdf, can be changed based on user feedback.
2.) Files for each run are collected and zipped into one folder named after the run. Csv files for config used, by-run simulation results, and summary stats are included in the folder. And user can choose downloading location by changing the download setting in browser. (We will try to control this when deploying from Chrome browser)
3.) Sample result plots are displayed using facets, allowing comparison for up to 4 different runs.
