### ISSUE TITLE
Add run summary

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH-UI#23]
The user may need some summary to be reminded which config components were edited for each run. This could be appear as a label in the results table, or as a figure description below the plots. We will explore options to capture and display this information.

**Comment by MeWu-IDM** [comment]
I have added UI description field and this information is saved to the runinfo.txt  but let's delay the decision of how to display it  in the next sprint

**Comment by BHagedorn-IDM** [comment]
Modification is to remove columns from results display table (start/end year, catchment pop). Replace these with the description text instead.

**Comment by MeWu-IDM** [comment]
if we don't get to test all plots , we will keep start/end year validation and add summary column

**Comment by MeWu-IDM** [comment]
@rhanIDM will remove the limitation of plots with different start/end year

**Comment by MeWu-IDM** [comment]
Partially done in https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/commit/f39e452abd520c8193b680c93c59ecbc2e040a12#diff-8077c0ddef2b67270cda7832e5a72ba805f8a0faf2cce8451774b10ed572de03
which add the summary column and remove max_utilization, hrs_per_wk and catchment_pop
we can remove start year /end year when plots can work with time gaps
