### ISSUE TITLE
Readme suggestions

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH-UI#30]
Installing through command prompt:
1. Add instructions for "Where to find cmd on your computer?"
2. When the user was asked to specify a path to store the UI, it was not clear that the user is creating a new folder and should provide a folder name.

**Comment by BHagedorn-IDM** [comment]
Step 6 in the instructions was confusing. I eventually figured out that I needed to go to the location pasted below to run the start_pace_ui file, but since it's named the same as the install, this was confusing. 
C:\Users\brittanyha\test\pace_hrh_ui\PACE-HRH-UI\PACE-HRH-UI-1.0.0

**Comment by BHagedorn-IDM** [comment]
Additional suggestion: Have text in step 3 (?) where the user providers the folder location, to write this down so they don't forget it.

**Comment by BHagedorn-IDM** [comment]
Make it clearer that if the double-click install works, you don't have to move into step 3.

**Comment by MeWu-IDM** [comment]
make step2 split to two scenario (1) double click -> skip to step 3 (2) comandline

**Comment by MeWu-IDM** [comment]
step 4 change reopen to launch

**Comment by MeWu-IDM** [comment]
step 6 : use launch (not restart) and ask user to go to the installation folder first

**Comment by MeWu-IDM** [comment]
step 6 changed to 
Make sure to go to folder of your choice from step3, then double click start_pace_ui.bat from your installed location
