### ISSUE TITLE
Setup should have update option

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#32]
Currently the setup script is only allowing fresh installation from user's chosen location, it does not support update scenario (when pace-hrh or pace-hrh-ui has updates), maybe we should have an option for user to reinstall when they select the same folder.

Current behavior: 
prompt user to enter a folder for installation -> if it exists, ask the user to choose another location

Suggest behavior:
prompt user to enter a folder for installation -> if it exists,  ask "An earlier version is installed in this location,  do you want to reinstall everything? " if user enters "yes" it will try to wipe out everything in this folder, if it failed to do so due to permission issue, it will ask the user to delete everything manually and start again, other wise it will attempt to use the same location to install.
If user enters "no", it will ask user to enter a new location instead.

Note, we can try to keep user's result data for now, but there is a risk that : if breaking change occurs (not all features can be backward compatible, user may not be able to load their previous results )

**Comment by BHagedorn-IDM** [comment]
Make sure that the previously run results are saved, and only the software package is replaced.

**Comment by MeWu-IDM** [comment]
this is in #41

**Comment by rhanIDM** [comment]
Installation testing feedback: 
1. README section "Installation and Run on windows without Git and Rstudio": add a separate section for step-by-step guide for update an existing version of pace-hrh-ui.
2. Add error handling for deleting files.
3. Add a warning to advise user to always make a copy of the results folder before initiating the update process.
4. Check conflicts with running R while updating.

**Comment by MeWu-IDM** [comment]
@rhanIDM 
I have fixed then
1. Separate Update.md
2-3. handle error by checking errorlevel and ask user to manually saved results and delete it
4. I tried running it with Rstudio open but cannot repro permission issue, I did changed one place that is when user exit the app, instead of killing R executable by name , use the exact R_path, so this script should not affect other R instances
