### ISSUE TITLE
Update plots

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#33]
Modify visuals to be clearer & change the PDF width based on number of plots.

**Comment by BHagedorn-IDM** [comment]
@MeWu-IDM I think we can close this, but please verify. I had pushed to the branch "plot-updates-UI" and I thought you said that you had manually merged those in a few weeks ago. I checked the current main branch and it looks to be running with the modifications. If you agree, then we can close that branch out and close this issue.

**Comment by MeWu-IDM** [comment]
got it, I think we are good


![Image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/40474438/72e44341-3d70-4c6d-b10e-7872958d31d1)
