### ISSUE TITLE
ggplotly() render failure

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH-UI#36]
Some plot types (geom_treemap) are not supported by ggplotly(), therefore such plot types should be avoided. We retired this plot type in Phase1 of UI release. All plots at this point should be supported by ggplotly().
To keep consistency of plot rendering, we should remove all references to ggplotTab() (the legacy plot rendering function) and archive ggplotTab.R

**Comment by MeWu-IDM** [comment]
moved ggplotTab.R to archive folder
https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/commit/f39e452abd520c8193b680c93c59ecbc2e040a12#diff-8077c0ddef2b67270cda7832e5a72ba805f8a0faf2cce8451774b10ed572de03
