### ISSUE TITLE
Run simulation processing window doesn't reset

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#44]
If I run a set of simulations, and then change the number of replications and select 'run' again, the status window does not close and reset. This means that I can't tell when the next set are complete or if the simulations are actually running in the background. Better functionality would be that if the window is open and I hit "run", that window should close/reset and then show the new run's status.

**Comment by MeWu-IDM** [comment]
closed this as it is fixed as : the log (in status window) will be cleared before the simulation when user "run" again that way he /she only sees the latest logs
