### ISSUE TITLE
Partner feedback: migrate existing results on another computer

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#46]
Currently we made an assumption that user's results are stored in the localstorage on their own client (browser) but for offline users, they may want to migrate existing results from some other machines. 
In order to add this we need to implement import/export from localstorage to json files and add logic to load it when the file is present

**Comment by MeWu-IDM** [comment]
For offline mode, results will not be copied over

**Comment by BHagedorn-IDM** [comment]
We are not going to do this at this time.
