### ISSUE TITLE
Partner feedback: Upload config from the UI

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#47]
Currently we are using demo_config as an example but user would like to have upload functionality for their own config, this seems trial but it may need some validation (or error handling ) oif user's config is not compatible

**Comment by BHagedorn-IDM** [comment]
Please add the following text to the config page: 

"If you would like to use your own configuration files, you can do so. This allows you to input different assumptions about your population pyramid, fertility and mortality rates, and specify a modified list of tasks and disease incidence rates. To do so, please see instructions from: https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/blob/main/Configuration.md."

**Comment by MeWu-IDM** [comment]
fixed https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/blob/3ee15761aa22f463a44ca8704dd1019969de6212/R/tooltips.R#L5-L12
