### ISSUE TITLE
Multi-page results inconsistent view

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#50]
When I have multiple pages of results and check the box next to one that is not on the first page, the selection works but then the view resets to the first page again. If I want to select multiple from a later page, then I have to repeatedly click back into the desired page. This is not desired behavior and the view that is currently on the page should remain when a run result tick box is clicked on/off.

**Comment by MeWu-IDM** [comment]
we need to store the page info from javascript and update it

**Comment by MeWu-IDM** [comment]
@BHagedorn-IDM  this is fixed in version 2.0.0 select from second page should not move the page anymore
