### ISSUE TITLE
Multi-page results can't show results

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#51]
When I have multiple pages of results, I can select runs but nothing appears to happen when I click "download results". 

When I have multiple pages of results, I can select runs but when I select "PDF plots" or "show/compare" I get an error message like the following. When I go to close the pop-up, the app crashes. My "pace_results" folder does not show any saved files for these runs, so I suspect they are getting deleted somehow?
![image](https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/assets/27299324/16972e9b-e220-4669-834a-085276978826)

The runs retain these problems even after I delete the first five results (previously on page 1) to move the "page 2" results back to page 1, so it must lose something permanently when they move to a later page.

**Comment by BHagedorn-IDM** [comment]
Note that this happened after I had run a bunch of results yesterday, then come back to review them today. Perhaps something was deleted/messed up in the meantime?

Update: I restarted the app and now it seems to work. So there is something incongruent happening when the app restarts (or possibly, crashes, which also happened in the interim). The names of the runs were still there in the results page, but the files seemed to have actually been deleted and didn't exist for accessing anymore.

**Comment by MeWu-IDM** [comment]
Hi, @BHagedorn-IDM  the "info missing" means that the result might not exist anymore (in bad state)
did you always start the app with the same port? 
when you delete it, the localstorage and physical files should be both deleted
I tried with 2 pages and the selection works for me, maybe you can show it to me on your machine

**Comment by BHagedorn-IDM** [comment]
Okay, we will leave this aside for now. It is an issue that will need to be resolved if this goes to production.
