### ISSUE TITLE
Cannot select the 5th result

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#52]
When I have multiple results in the results page, I cannot select the checkbox next to the 5th one in the list. It seems to select/unselect rapidly, as I see something of a flicker when I click.

**Comment by BHagedorn-IDM** [comment]
Update: I restarted the program and now I can only select the first two out of five. So the issue is the same, but it's not consistent. And now that I've shown the results in the plots below, I can't unselect the top two.

**Comment by MeWu-IDM** [comment]
@BHagedorn-IDM yes actually now we limit only 4 for comparison, do you want to allow more? this is an easy fix

**Comment by MeWu-IDM** [comment]
should be fixed in https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/pull/59/commits/81b27003a20f69e317d1607badd41783e2b8aeab

**Comment by MeWu-IDM** [comment]
closed as fixed (now you can select more than 4 for deletion but only up to 4 for data comparison)
