### ISSUE TITLE
Cannot delete the last results entry

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH-UI#53]
When I have only one result run in the list, I can select "delete" and confirm that I want to take this action, but it is not actually removed from the list.

**Comment by MeWu-IDM** [comment]
I have not been able to repro but I did see plots were not cleared if they were rendered before. need investigation

**Comment by MeWu-IDM** [comment]
@BHagedorn-IDM please try again on the same port, see https://github.com/InstituteforDiseaseModeling/PACE-HRH-UI/blob/main/README.md#run-the-app-locally
assign to me if you still cannot delete

**Comment by BHagedorn-IDM** [comment]
Resolved.
